name: "Test of including custom action"

on: [workflow_dispatch]

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Run custom Action"
        uses: ./.github/actions/hello-world-action

      - name: "Include JS Action"
        uses: ./.github/actions/js-action
        with:
          user-name: 'Tony Montana'
      
