name: testing scripts
run-name: trying scripts
on: [workflow_dispatch]
jobs:  
  init_script:
    name: script init
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: List files in .github/scripts directory
        run: |
          echo `cat first.txt`
          echo "$(ls -al /home/runner/work/test-workflows)"
      
      - name: run build script
        shell: bash
        run: |
          ${{ github.workspace }}/.github/scripts/script.sh > result.txt 
      - name: upload the result
        uses: actions/upload-artifact@v3
        with:
          name: result
          path: result.txt
  
  print_result:
    name: show result
    runs-on: ubuntu-latest
    needs: init_script
    steps:
      - name: download the result
        uses: actions/download-artifact@v3
        with:
          name: result
      - name: print
        run: |
          result=`cat result.txt`
          echo result
    
